# About the author {-}

J. Kevin Corder is a professor of political science at Western Michigan University in Kalamazoo. His research has appeared in the *American Political Science Review*, *The Journal of Politics*, and other outlets in political science and public administration. Much of his work focuses on economic policy, including two books on the Federal Reserve System. In 2013, Dr. Corder received a Fulbright–Schuman European Affairs program grant to study the regulation of banks in Malta and the United Kingdom. He shared a National Science Foundation grant and the Carrie Chapman Catt prize with Christina Wolbrecht, University of Notre Dame.  They are the authors of **Counting Women’s Ballots: Female Voters from Suffrage through the New Deal** and **A Century of Votes for Women: American Elections since Suffrage** (both Cambridge University Press).  Both books were recognized with the American Political Science Association Victoria Schuck prize for the best book on women and politics in the calendar year.
